version: '3.8'

services:
  web:
    container_name: users_api
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://manager:manager@localhost:5432/dbusers
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=manager
      - POSTGRES_DB=dbusers
      - POSTGRES_HOST=localhost
volumes:
  postgres_data: